framework:

    messenger:
        reset_on_message: true

    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: true
        cookie_samesite: 'none'

    #esi: true
    #fragments: true
    php_errors:
        log: true
