<?php

namespace App\Services;

use CidiLabs\PhpAlly\PhpAllyIssue;
use CidiLabs\PhpAlly\PhpAllyReport;

use App\Entity\Issue;
use App\Entity\ContentItem;
use Symfony\Component\Console\Output\ConsoleOutput;

/*
    Given a JSON report generated by accessibility-checker,
    parse the JSON for all failed rules (according to Equal Access)
    and put them in a phpAlly report
*/

class EqualAccessService {

    private function getSkipRules() {
        $backupRules = "
            html_lang_exists,
            html_skipnav_exists,
            page_title_exists,
            skip_main_exists,
            style_highcontrast_visible,
            style_viewport_resizable,
            aria_accessiblename_exists,
            aria_content_in_landmark, 
            aria_landmark_name_unique,
            a_target_warning,
            text_quoted_correctly
        ";

        $skipRules = !empty($_ENV['EQUALACCESS_EXCLUDED_RULES']) ? $_ENV['EQUALACCESS_EXCLUDED_RULES'] : $backupRules;
        $skipRules = explode(",", $skipRules);
        foreach ($skipRules as &$rule) {
            $rule = trim($rule);
        };

        return $skipRules;
    }

    public function logToServer(string $message) {
        $options = [
            'http' => [
                'header' => "Content-type: text/html\r\n",
                'method' => 'POST',
                'content' => $message,
            ],   
        ];
        
        $context = stream_context_create($options);
        file_get_contents("http://host.docker.internal:3000/log", false, $context);
    }

    // Generate a UDOIT-style JSON report from the output of Equal Access
    public function generateReport($json) {

        $report = new PhpAllyReport();
        $output = new ConsoleOutput();

        $issues = array();
        $issueCounts = array();
        $skipRules = $this->getSkipRules();
        
        foreach ($json["results"] as $results) {
            $equalAccessRule = $results["ruleId"];
            $xpathQuery = $results["path"]["dom"];
            $metadata = null;

            // First check if the HTML has phpally-ignore and also check if the rule isn't one we skip.
            if (!in_array($equalAccessRule, $skipRules)) {
                // Populate the issue counts field with how many total issues
                // with the specific rule are found
                if (array_key_exists($equalAccessRule, $issueCounts)) {
                    $issueCounts[$equalAccessRule]++;
                }
                else {
                    $issueCounts[$equalAccessRule] = 1;
                }

                $reasonId = $results["reasonId"];
                $message = $results["message"];
                $messageArgs = $results["messageArgs"];
                $value = $results["value"];

                $metadata = $this->createMetadata($reasonId, $message, $messageArgs, $value);
                
                // $issue = new PhpAllyIssue($equalAccessRule, $issueHtml, $parentIssueHtml, $metadata);
                $issue = (object) [
                  'isGeneric' => true,
                  'scanRuleId' => $equalAccessRule,
                  'xpath' => $xpathQuery,
                  'metadata' => $metadata,
                ];
                $report->setIssueCounts($equalAccessRule, $issueCounts[$equalAccessRule], -1);
                array_push($issues, $issue);
                $report->setErrors([]);
            }
        }

        $report->setIssues($issues);

        return $report;
    }

    public function createMetadata($reasonId, $message, $messageArgs, $value) {
        // The Equal Access report has a few sections which describe
        // what the error is/what type of error/error arguments, which we can use 
        // on UFIXIT to display messages

        $metadata = array(
            "reasonId" => $reasonId,
            "message" => $message,
            "messageArgs" => $messageArgs,
            "value" => $value,
        );

        return json_encode($metadata);
    }

    public function getIssueType($metadata) {
      // if we're using equal access, use the "value" types (usually an array like ["VIOLATION", "FAIL"])
      // to set the issue type (e.g. "error" or "suggestion")
      $metadata = json_decode($metadata, true);
      $value = $metadata["value"];

      if (is_array($value)) {
        /* equal access has the following: violation, potentialviolation, recommendation, potentialrecommendation, manual
        violation, potentialviolation -> issue, potential issue
        recommendation, potentialrecommendation -> suggestion
        manual -> potential issue 
        */
        if (in_array("PASS", $value)) {
          return "pass";
        }
        else if (in_array("MANUAL", $value)) {
          // potentialviolation
          // manual is a special case, it means that the rule requires manual review
          return "potential";
        }
        else if (in_array("VIOLATION", $value)) {
          if (in_array("FAIL", $value)) {
            // violation
            return "error";
          }
          else {
            // potentialviolation
            return "potential";
          }
        }
        else if (in_array("RECOMMENDATION", $value)) {
          // recommendation/potentialrecommendation
          return "suggestion";
        }
      }

      return "error";
    }
}
