FROM nginx:latest
COPY ./deploy/default.conf /etc/nginx/conf.d/default.conf

FROM php:8.1-fpm

# PHP extensions
RUN apt-get update && apt-get install -y libpng-dev zlib1g-dev git unzip
RUN docker-php-ext-install gd pdo pdo_mysql
COPY . /var/www/html
