<?php
/**
*   Copyright (C) 2014 University of Central Florida, created by Jacob Bates, Eric Colon, Fenel Joseph, and Emily Sachs.
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*   Primary Author Contact:  Jacob Bates <jacob.bates@ucf.edu>
*/
class UdoitStats
{
    private static $instance;

    public static function instance()
    {
        if (!isset(self::$instance)) {
            self::$instance = new UdoitStats();
        }

        return self::$instance;
    }

    /**
     * Gets a list of reports (scans)
     * 
     * @param  startDate    Earliest date of report to include
     * @param  endDate      Latest date of report to include
     * @param  term         (Optional) Only include reports generated for courses within this Canvas term ID
     * @param  course_id    (Optional) Only include reports corresponding to this Canvas course ID
     * @param  user_id      (Optional) Only include reporst generated by this Canvas user ID
     */
    public function getReports($startDate, $endDate, $term=false, $course_id=false, $user_id=false)
    {

    }

    /**
     * Gets the latest report from each course, and counts how many issues (errors + suggestions)
     * were found in that report.
     * 
     * @param  startDate    Earliest date of report to include
     * @param  endDate      Latest date of report to include
     * @param  term         (Optional) Only include reports generated for courses within this Canvas term ID
     * @param  user_id      (Optional) Only include reporst generated by this Canvas user ID
     */
    public function countIssuesPerCourse($startDate, $endDate, $term=false, $user_id=false)
    {

    }

    /**
     * Tallys up number of reports generated (scans performed) by each user
     * @param  grain        How granular the tally is.  Accepted values: day, week, month
     * @param  startDate    Earliest date of report to include
     * @param  endDate      Latest date of report to include
     * @param  term         (Optional) Only include reports generated for courses within this Canvas term ID
     */
    public function countReportsPerUser($grain, $startDate, $endDate, $term=false)
    {

    }

    /**
     * Tallys up number of new users per period defined by grain.
     * @param  grain        How granular the tally is.  Accepted values: day, week, month
     * @param  startDate    (DateTime) Earliest date of report to include
     * @param  endDate      (DateTime) Latest date of report to include
     */
    public function countNewUsers($grain, $startDate, $endDate)
    {
        global $db_user_table;

        // Set up the date format to group the results properly
        // TODO: Make sure this is compatible with Postgres (using to_char) and sqlite
        switch ($grain) {
            case 'day':
                $date_format = 'DATE_FORMAT(date_created, \'%Y-%m-%d\')';
                break;
            case 'week':
                $date_format = 'DATE_FORMAT(date_created, \'%X-%V\')';
                break;
            case 'month':
                $date_format = 'DATE_FORMAT(date_created, \'%Y-%m\')';
                break;
            case 'year':
                $date_format = 'DATE_FORMAT(date_created, \'%Y\')';
                break;
            default:
                // Default to daily
                $date_format = 'DATE_FORMAT(date_created, \'%Y-%m-%d\')';
        }

        $sth = UdoitDB::prepare("
            SELECT COUNT(1) AS users, {$date_format} AS date
            FROM users
            WHERE DATE(date_created) >= :startdate
            AND DATE(date_created) <= :enddate
            GROUP BY {$date_format}
            ");
        $sth->bindValue($startDate->format('Y-m-d'), 'startdate', PDO::PARAM_STR);
        $sth->bindValue($endDate->format('Y-m-d'), 'enddate', PDO::PARAM_STR);

        if ($sth->execute()) {
            return $sth->fetchAll(PDO::FETCH_ASSOC);
        }
        
        return false;
    }

    /**
     * Gets every user in the database.
     *
     * @return Associative array of results, false on error
     */
    public function getUsers()
    {
        //TODO:  Paginate this by adding a page parameter and modifying the query
        global $db_user_table;

        $sth = UdoitDB::prepare("SELECT id, date_created, canvas_url FROM {$db_user_table}");       

        if ($sth->execute()) {
            return $sth->fetchAll(PDO::FETCH_ASSOC);
        }
        return false;
    }
}