version: '3.3'

services:
  db:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: udoit3
      MYSQL_USER: udoit
      MYSQL_PASSWORD: udoit
    ports:
      - "3306:3306"
  # Uncomment this block and comment the next db block
  # to use Postgres instead of MySQL
  # db:
  #   image: postgres:alpine
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: udoit
  #     POSTGRES_PASSWORD: udoit
  #     POSTGRES_DB: udoit3
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
volumes:
  web:
  dbdata:
